import os
import sys
import requests
import google.generativeai as genai

def setup_brain():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY missing.")
        sys.exit(1)
    genai.configure(api_key=api_key)
    
    # Auto-select the best Flash model
    best_flash_model = "gemini-2.5-flash"
    for m in genai.list_models():
        if 'generateContent' in m.supported_generation_methods and 'flash' in m.name.lower() and 'exp' not in m.name.lower():
            best_flash_model = m.name
            break
    return genai.GenerativeModel(best_flash_model)

def parse_github_url(url):
    # Extracts owner, repo, and issue number from a standard GitHub Issue URL
    # Example: https://github.com/owner/repo/issues/123
    parts = url.rstrip('/').split('/')
    if "issues" in parts:
        issue_index = parts.index("issues")
        owner = parts[issue_index - 2]
        repo = parts[issue_index - 1]
        issue_number = parts[issue_index + 1]
        return owner, repo, issue_number
    return None, None, None

def get_issue_context(owner, repo, issue_number, github_token):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}"
    headers = {"Authorization": f"token {github_token}", "Accept": "application/vnd.github.v3+json"}
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch issue context. Status: {response.status_code}")
        return None

def generate_solution(model, issue_title, issue_body):
    prompt = f"""
    You are the Sovereign Skein, an advanced Web3 developer AI. 
    Analyze the following GitHub Issue which has been flagged as a bounty.
    
    Issue Title: {issue_title}
    Issue Body: {issue_body}
    
    Provide a highly technical, helpful, and concise response. If it's a bug, suggest the code fix. If it's a structural question, provide an architectural breakdown.
    Do NOT use conversational filler. Be strictly professional. 
    """
    response = model.generate_content(prompt)
    
    # The Transparency Armor
    disclaimer = "\n\n---\n*This analysis was autonomously generated by the Sovereign Skein agent to assist the open-source Web3 community.*"
    return response.text.strip() + disclaimer

def execute_strike(owner, repo, issue_number, comment_body, github_token):
    print(f"Executing payload on {owner}/{repo} Issue #{issue_number}...")
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    headers = {
        "Authorization": f"token {github_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    payload = {"body": comment_body}
    
    response = requests.post(url, headers=headers, json=payload)
    if response.status_code == 201:
        print("SUCCESS: Mission Accomplished. Comment posted and identity secured.")
    else:
        print(f"FAILED to post comment. Status: {response.status_code} - {response.text}")

def main():
    # We will pass the target URL as an environment variable from GitHub Actions
    target_url = os.getenv("TARGET_ISSUE_URL")
    github_token = os.getenv("SKEIN_GITHUB_TOKEN")
    
    if not target_url or not github_token:
        print("Error: TARGET_ISSUE_URL or SKEIN_GITHUB_TOKEN not provided.")
        sys.exit(1)

    print(f"Target locked: {target_url}")
    owner, repo, issue_number = parse_github_url(target_url)
    
    if not owner:
        print("Invalid GitHub Issue URL format.")
        sys.exit(1)

    # 1. Gather Intel
    issue_data = get_issue_context(owner, repo, issue_number, github_token)
    if not issue_data:
        sys.exit(1)
        
    # 2. Formulate Solution
    model = setup_brain()
    solution = generate_solution(model, issue_data.get('title'), issue_data.get('body'))
    
    # 3. Execute
    execute_strike(owner, repo, issue_number, solution, github_token)

if __name__ == "__main__":
    main()
